site_name: Aircraft Guide
site_url: https://mydomain.org/website

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - def_list
  - tables

extra_css:
  - stylesheets/extra.css

theme:
  name: lux
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
  analytics:
    provider: google
    property: G-WWK6YP3W8L

nav:
  - World War I: world-war-i.md
  - World War II: world-war-ii.md
  - Cold War: cold-war.md
  - Modern Day: modern-day.md
  